Fix errror

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,45 +1,65 @@
-name: CD Pipeline
+name: CI Pipeline
 
 on:
   push:
     branches: ['develop']
-  workflow_run:
-    workflows: ['CI Pipeline']
-    types:
-      - completed
+  pull_request:
+    branches: ['develop']
 
 jobs:
-  build:
-    runs-on: self-hosted
+  build-and-test:
+    runs-on: ubuntu-latest
 
     steps:
-      - name: Clean up disk space
+      # Checkout du code source
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      # Installation de Node.js
+      - name: Setup Node.js
+        uses: actions/setup-node@v2
+        with:
+          node-version: '22'
+
+      # Installation des dépendances
+      - name: Install dependencies
+        run: npm install --legacy-peer-deps
+
+      # Vérification des paquets installés (optionnel)
+      - name: Check installed packages
+        run: npm list --depth=0
+
+      # Exécution des tests
+      - name: Run Tests
         run: |
-          # Eliminar imágenes Docker no utilizadas y contenedores detenidos
-          sudo docker system prune -af --volumes
-          
-          # Verificar espacio disponible después de la limpieza
-          df -h /
+          npm run test || { echo 'Tests failed'; exit 1; }
 
-      - name: Pull Docker image
-        run: sudo docker pull bilanox/moride:latest
+      # Connexion à Docker Hub
+      - name: Login to Docker Hub
+        env:
+          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
+          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
+        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
 
-      - name: Ensure Old Docker Container is Stopped and Removed
-        run: |
-          sudo docker stop moride-container || true
-          sudo docker rm -f moride-container || true
-
-      - name: Check if port 3000 is in use
-        run: |
-          if sudo ss -tuln | grep -q ':3000'; then
-            echo "Port 3000 is in use. Stopping conflicting container or process."
-            sudo fuser -k 3000/tcp || true
-          fi
-
-      - name: Create .env file
+      # Construction de l'image Docker
+      - name: Build Docker image
+        env:
+          DATABASE_URL: ${{ secrets.DATABASE_URL }}
+          PORT: ${{ secrets.PORT }}
+          jwtConstants: ${{ secrets.jwtConstants }}
+          JWT_SECRET: ${{ secrets.JWT_SECRET }}
+          JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}
+          CLOUDINARY_NAME: ${{ secrets.CLOUDINARY_NAME }}
+          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
+          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
+          SMTP_HOST: ${{ secrets.SMTP_HOST }}
+          SMTP_PORT: ${{ secrets.SMTP_PORT }}
+          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
+          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
+          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
+          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
         run: |
           echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
-          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
           echo "PORT=${{ secrets.PORT }}" >> .env
           echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
           echo "JWT_EXPIRES_IN=${{ secrets.JWT_EXPIRES_IN }}" >> .env
@@ -52,7 +72,8 @@ jobs:
           echo "SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}" >> .env
           echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
           echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
-          echo "NODE_ENV=production" >> .env
+          docker build -t bilanox/moride:latest .
 
-      - name: Run Docker Container with .env
-        run: sudo docker run -d -p ${{ secrets.PORT }}:3000 --env-file .env --name moride-container bilanox/moride
+      # Push de l'image sur Docker Hub
+      - name: Push to Docker Hub
+        run: docker push bilanox/moride:latest
